//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.12 at 12:31:05 PM IST 
//


package xmlpojo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xsdfilescustomerdetails package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Accountdetails_QNAME = new QName("", "accountdetails");
    private final static QName _Customerinfo_QNAME = new QName("", "customerinfo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xsdfilescustomerdetails
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Accountdetails }
     * 
     */
    public Accountdetails createAccountdetails() {
        return new Accountdetails();
    }
    
    public Customerinfo createCustomerinfo() {
        return new Customerinfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Accountdetails }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "accountdetails")
    public JAXBElement<Accountdetails> createAccountdetails(Accountdetails value) {
        return new JAXBElement<Accountdetails>(_Accountdetails_QNAME, Accountdetails.class, null, value);
    }
    
    @XmlElementDecl(namespace = "", name = "customerinfo")
    public JAXBElement<Customerinfo> createCustomerInfo(Customerinfo value) {
        return new JAXBElement<Customerinfo>(_Customerinfo_QNAME, Customerinfo.class, null, value);
    }

}
