//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.12 at 12:31:05 PM IST 
//


package sathya.output;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xsdfilescustomerdetails package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PersonalDetails_QNAME = new QName("", "personaldetails");
   
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xsdfilescustomerdetails
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Accountdetails }
     * 
     */
  


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Accountdetails }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "accountdetails")
    public JAXBElement<PersonalDetails> createPersonalDetails(PersonalDetails value) {
        return new JAXBElement<PersonalDetails>(_PersonalDetails_QNAME, PersonalDetails.class, null, value);
    }
   

}
